### ISSUE TITLE
No Telegram messages on Google Cloud deployment

### ISSUE THREAD

**Issue by nilsh7** [flathunters/flathunter#62] opened 2020-09-27 19:48 UTC
First of all, thank you all for this great project.

I have deployed the app as a cron job to Google Cloud and when accessing via the webpage, I do see new listings coming in. However I have not received a message from the Telegram bot yet. I ran the program locally first and it worked fine and sent me Telegram messages. So I think my `config.yaml` should be fine. The Google Cloud dashboard does not show any errors and that the `/hunt` url was triggered 149 times in the last 24 hours.

Any clue of where my error might be?

**Comment by codders** [comment] 2020-09-30 10:23
Do you see any logs from the SenderTelegram class? You could try deploying the app with config 'verbose: true' and see if you see more messages. You might also need to upgrade your plan on Google Cloud and associate the project with a billing account. You can still run the app without paying any money, but Google blocks some external network access if you don't have a credit card somewhere linked to the project.

**Comment by nilsh7** [comment] 2020-09-30 15:36
I took a look into the logs in GoogleCloud and found the following error:
```
When sending bot message, we got status 400 with message: {'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'}
```
I tried some things like adding a `-` sign before the chat ID or adding the bot again in a telegram chat. None of which helped.

I also checked my Google Cloud account and the project is listed under Billing and the billing account is linked to the project.

**Comment by nilsh7** [comment] 2020-10-01 07:40
It does have numbers before the colon, but after it there is no hyphen and a mixture of letter and numbers. So it looks like 1111111111:XXxxXX1XxxxXX_XX1xxXxxXxxX1xXxX.

**Comment by fw349** [comment] 2020-12-23 15:17
Got pretty much the same issue - can see new flats appear on the webpage when running with gcloud, yet I can't receive messages via telegram - any further ideas why this could be and what could be done against it?

**Comment by fw349** [comment] 2020-12-30 21:07
I'm still struggling with this issue...does anyone have an answer? I had the error message "FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/chromedriver': '/usr/local/bin/chromedriver'" yet there is chromedriver installed (with homebrew) and exactly at that location...?

**Comment by adlaube** [comment] 2021-02-15 18:35
Duplicate of #35 
I posted a dirty hotfix there

**Comment by codders** [comment] 2021-02-16 17:52
I've merged a fix for this, per the suggestion from @adlaube . Please retest with the latest master and let me know if that makes life better for you. Thanks @adlaube !

**Comment by alexanderroidl** [comment] 2022-07-25 22:44
As there has not been another response, we will regard this issue to be solved. 😌

**Closed by alexanderroidl** 2022-07-25 22:44 UTC
