### ISSUE TITLE
flathunter / chromedriver on headles system?

### ISSUE THREAD

**Issue by pcace** [flathunters/flathunter#83] opened 2020-10-16 11:28 UTC
HI,

first of all, do i understand it correctly, that i can use the new captacha resolv methode also on a headless system?
i am on a debian system and downloaded chromedriver from here (https://chromedriver.storage.googleapis.com/index.html?path=87.0.4280.20/) wich seems to work:

```
Starting ChromeDriver 87.0.4280.20 (c99e81631faa0b2a448e658c0dbd8311fb04ddbd-refs/branch-heads/4280@{#355}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
```
i also installed chromium. when i start flathunter now i get the following error message:
```

python3 flathunt.py 
[2020/10/16 13:24:52|config.py         |INFO    ]: Using config /home/user/flathunter/config.yaml
Traceback (most recent call last):
  File "flathunt.py", line 89, in <module>
    main()
  File "flathunt.py", line 68, in main
    config = Config(config_handle.name)
  File "/home/user/flathunter/flathunter/config.py", line 29, in __init__
    self.__searchers__ = [CrawlImmobilienscout(self),
  File "/home/user/flathunter/flathunter/crawl_immobilienscout.py", line 42, in __init__
    self.driver = self.configure_driver(self.driver_executable_path, self.driver_arguments)
  File "/home/user/flathunter/flathunter/abstract_crawler.py", line 51, in configure_driver
    driver = webdriver.Chrome(executable_path=driver_path, options=chrome_options)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /usr/bin/chromium unexpectedly exited. Status code was: 1

```

any idea what to do here?

Thanks a lot!!

**Comment by codders** [comment] 2020-10-18 11:10
Hey @pcace,

I would expect this to work on a headless system, assuming Chromium headless is working. But it looks like for whatever reason it isn't working on your system.

Do you have matching versions of Chromium and the ChromeDriver? It can be pretty fussy about getting an exact version match.

**Comment by arubacao** [comment] 2020-10-18 17:24
I can confirm that flathunter is working with a Chromium headless browser.

**Comment by pcace** [comment] 2020-10-19 14:55
> I can confirm that flathunter is working with a Chromium headless browser.

Hi, can you tell me more about your system / chromium / Chromedriver Versions?

Thanks a lot!!

**Comment by pcace** [comment] 2020-10-19 15:14
Hi,

i got one step further, but i now dont know if it has something to do with the chromedriver issue i had earlier, or if this is another problem. Does anyone have an idea?
Cheers and thanks!!!

```
user@mail:~/flathunter$ python3 flathunt.py
[2020/10/19 17:11:23|config.py         |INFO    ]: Using config /home/user/flathunter/config.yaml
[2020/10/19 17:11:24|flathunt.py       |DEBUG   ]: Settings from config: <flathunter.config.Config object at 0x7f53340a8d30>
[2020/10/19 17:11:24|crawl_immobilienscout.py|DEBUG   ]: Got search URL https://www.immobilienscout24.de/Suche/shape/wohnung-mieten?shape=dX1sX0lxe2BwQXpqRWlmRGZmQG97QnBBfXFUX3BBb3dEZVl7S3loQHJjQXtkQmdxRXFyQT93ZEZ6ZU1xcEBiZ0hsZUFocUVyQXBuQnZoQHpLdGpBbnlD&numberofrooms=3.0-&price=-1800.0&livingspace=80.0-&enteredFrom=result_list#/&pagenumber={0}
[2020/10/19 17:11:26|abstract_crawler.py|DEBUG   ]: Google site key: <re.Match object; span=(49, 93), match='&k=6LeaILIZAAAAALTgLZV1AQXPc2dAsLItNYJ8jVvB&'>
[2020/10/19 17:11:31|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/19 17:11:36|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/19 17:11:43|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/19 17:11:48|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/19 17:11:53|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/19 17:11:58|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/19 17:12:03|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/19 17:12:08|abstract_crawler.py|DEBUG   ]: Captcha status: CAPCHA_NOT_READY
[2020/10/19 17:12:08|abstract_crawler.py|DEBUG   ]: Captcha promise: OK|03AGdBq27gcEuhzq2nOQbJFWNoBttj8ScdLWSDUvUIWl8FQmrZNyMjp1_O_WsRDFc6Q65tYtvyDRXh2W4a0z7GX0sS1XfqTHGfF_-9kpXHLJWtrf1Qh9Wd2GglUMbJr2EwXroMds_4AZT3wVbWxXKq4hkALme-LUR6cRuiQLX0vt53xWFNbEHRsH9e-yENqtVFl07z-jqqaJELBF-TDZkeGbGyPnoePx_44Wv6qm7mh1iN1pKx_2-oOn83qUx2MNMQ_8BTLPXbEqtZ61Y83Hylr-pzDF3hAOCNZpDRsgTMPT7DYCWZRTOxh_G1pmLXZKl2FihVRJMgzvW4b3vQqt4watElB6pJM4JwHMc9JZmlQyCe5KhA-pPUVippbB6g0N7ZQJ09oVVL8nKV4OIfxAIXVHW3-lDB3FjYzlotiKfHwOduCLQdPaZiVSeBrg2kr-DChldW1QsBsHpG8St-ZISHzwyRjDFphah5G8GgxfjdxUsOoxLbddO_QsfTQRshM_Z1cGlcUf8YeyHiVbH2kdKBc5MP6GRBDf2KHKdMTsga0BAtRP4Ep9kKtHo
Traceback (most recent call last):
  File "flathunt.py", line 89, in <module>
    main()
  File "flathunt.py", line 86, in main
    launch_flat_hunt(config)
  File "flathunt.py", line 46, in launch_flat_hunt
    hunter.hunt_flats()
  File "/home/user/flathunter/flathunter/hunter.py", line 42, in hunt_flats
    for expose in processor_chain.process(self.crawl_for_exposes(max_pages)):
  File "/home/user/flathunter/flathunter/hunter.py", line 22, in crawl_for_exposes
    for searcher in self.config.searchers()
  File "/home/user/flathunter/flathunter/hunter.py", line 23, in <listcomp>
    for url in self.config.get('urls', list())])
  File "/home/user/flathunter/flathunter/abstract_crawler.py", line 136, in crawl
    return self.get_results(url, max_pages)
  File "/home/user/flathunter/flathunter/crawl_immobilienscout.py", line 63, in get_results
    return self.get_entries_from_javascript()
  File "/home/user/flathunter/flathunter/crawl_immobilienscout.py", line 105, in get_entries_from_javascript
    return [ self.extract_entry_from_javascript(entry) for entry in entry_list ]
  File "/home/user/flathunter/flathunter/crawl_immobilienscout.py", line 105, in <listcomp>
    return [ self.extract_entry_from_javascript(entry) for entry in entry_list ]
  File "/home/user/flathunter/flathunter/crawl_immobilienscout.py", line 115, in extract_entry_from_javascript
    'price': str(entry["resultlist.realEstate"]["monthlyRate"]),
KeyError: 'monthlyRate'
user@mail:~/flathunter$
```

**Comment by arubacao** [comment] 2020-10-19 16:58
Looks like your chromedriver is now working properly. 
I'm having this "new" issue today and https://github.com/flathunters/flathunter/issues/85 as well.

**Comment by codders** [comment] 2020-10-19 17:50
Yes. This looks like #85. Closing this issue for now.

**Closed by codders** 2020-10-19 17:50 UTC
