### ISSUE TITLE
abstract_crawler.py|ERROR   ]: Connection failed for proxy XXX Trying new proxy

### ISSUE THREAD

**Issue by Sashimisu** [flathunters/flathunter#157] opened 2022-03-09 11:34 UTC
Hi Guys,

I am new to python and running script from GitHub in general.
Could you please tell me if this is correct? I've had this running for hours, but nothing seems to be changing.
![image](https://user-images.githubusercontent.com/101259292/157433997-072efec4-2e82-42e2-bc43-df0155f3fc6f.png)

**Comment by codders** [comment] 2022-03-09 12:31
Looks like you might have a bad internet connection from your device.

You could try configuring it not to use the proxy servers - that might get
rid of these errors.

**Comment by Sashimisu** [comment] 2022-03-10 13:25
I changed the settings for the proxy servers to False, but I keep getting this notice
![image](https://user-images.githubusercontent.com/101259292/157670928-5efeecb9-006c-4968-90e0-b219effbff34.png)

**Comment by codders** [comment] 2022-03-10 17:54
That looks more promising. We had another user issue report about captcha problems this week. They said there was a problem with the 2captcha service. (#158) That was also fixed today - maybe yours will start working too?

If it's still not working tomorrow, we'll have to dig more into the code.

**Comment by iwasherefirst2** [comment] 2022-04-07 05:15
The issue that about index out of range has actually nothing to do with #158 as this is caused by a 500 serve error response. I would suggest to close this ticket and continue the discussion how to fix the split error in https://github.com/flathunters/flathunter/issues/162

**Comment by ozeidan** [comment] 2022-04-08 14:32
This was fixed by #161.
Side note: seems like we live in the same street @Sashimisu 👀 😂

**Comment by mordax7** [comment] 2022-05-29 14:28
Closing since fixed

**Closed by mordax7** 2022-05-29 14:28 UTC
