### ISSUE TITLE
Trying to install on Mac OS: Mapping values are not allowed here 

### ISSUE THREAD

**Issue by patowod** [flathunters/flathunter#572] opened 2024-04-19 14:31 UTC
Hi all, I am trying my best to getting this to work (a bit of code experience, but by no means a coder ;) I got everything installed but can not complete the wizard or even use the example config from this repo. This is what my environment looks like and what I get:

Mac OS, Python 3.12.2, Pipenv installed via homebrew and cloned the repository. After that I followed the documentation up to the point where python config_wizard.py should start the wizard - which it does, but after the first enter it aborts with the following. It aborts no matter if there is a config.yaml present or if not:

`pow@pow flathunter % pipenv shell
Launching subshell in virtual environment...
 . /Users/pow/.local/share/virtualenvs/flathunter-2YKm7R8n/bin/activate
pow@pow flathunter %  . /Users/pow/.local/share/virtualenvs/flathunter-2YKm7R8n/
bin/activate
(flathunter) pow@pow flathunter % python config_wizard.py
Traceback (most recent call last):
  File "/Users/pow/flathunter/config_wizard.py", line 315, in <module>
    main()
  File "/Users/pow/flathunter/config_wizard.py", line 297, in main
    config = load_config(existing)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pow/flathunter/config_wizard.py", line 266, in load_config
    config = yaml.load(dist_config)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pow/.local/share/virtualenvs/flathunter-2YKm7R8n/lib/python3.12/site-packages/ruamel/yaml/main.py", line 451, in load
    return constructor.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pow/.local/share/virtualenvs/flathunter-2YKm7R8n/lib/python3.12/site-packages/ruamel/yaml/constructor.py", line 112, in get_single_data
    node = self.composer.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pow/.local/share/virtualenvs/flathunter-2YKm7R8n/lib/python3.12/site-packages/ruamel/yaml/composer.py", line 70, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pow/.local/share/virtualenvs/flathunter-2YKm7R8n/lib/python3.12/site-packages/ruamel/yaml/composer.py", line 92, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pow/.local/share/virtualenvs/flathunter-2YKm7R8n/lib/python3.12/site-packages/ruamel/yaml/composer.py", line 128, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pow/.local/share/virtualenvs/flathunter-2YKm7R8n/lib/python3.12/site-packages/ruamel/yaml/composer.py", line 209, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pow/.local/share/virtualenvs/flathunter-2YKm7R8n/lib/python3.12/site-packages/ruamel/yaml/composer.py", line 128, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pow/.local/share/virtualenvs/flathunter-2YKm7R8n/lib/python3.12/site-packages/ruamel/yaml/composer.py", line 209, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pow/.local/share/virtualenvs/flathunter-2YKm7R8n/lib/python3.12/site-packages/ruamel/yaml/composer.py", line 104, in compose_node
    if self.parser.check_event(AliasEvent):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pow/.local/share/virtualenvs/flathunter-2YKm7R8n/lib/python3.12/site-packages/ruamel/yaml/parser.py", line 139, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/Users/pow/.local/share/virtualenvs/flathunter-2YKm7R8n/lib/python3.12/site-packages/ruamel/yaml/parser.py", line 791, in parse_flow_mapping_empty_value
    return self.process_empty_scalar(self.scanner.peek_token().start_mark)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pow/.local/share/virtualenvs/flathunter-2YKm7R8n/lib/python3.12/site-packages/ruamel/yaml/scanner.py", line 1747, in peek_token
    self._gather_comments()
  File "/Users/pow/.local/share/virtualenvs/flathunter-2YKm7R8n/lib/python3.12/site-packages/ruamel/yaml/scanner.py", line 1774, in _gather_comments
    self.fetch_more_tokens()
  File "/Users/pow/.local/share/virtualenvs/flathunter-2YKm7R8n/lib/python3.12/site-packages/ruamel/yaml/scanner.py", line 277, in fetch_more_tokens
    return self.fetch_value()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/pow/.local/share/virtualenvs/flathunter-2YKm7R8n/lib/python3.12/site-packages/ruamel/yaml/scanner.py", line 627, in fetch_value
    raise ScannerError(
ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
  in "config.yaml", line 110, column 17`

**Comment by bbenzo** [comment] 2024-05-03 12:17
Ran into the same issue. As an alternative you can simply follow the readme section here to create the config file manually: https://github.com/flathunters/flathunter/?tab=readme-ov-file#configuration

**Comment by codders** [comment] 2024-05-09 15:44
Looks like the same issue as #576  . I think I've resolved with with #586 - please fetch the latest code and retry, and let me know if the issue isn't resolved. 

Thanks for the report!

**Comment by codders** [comment] 2024-05-13 16:00
Closing this as resolved - please reopen it if it turns out not to be fixed.

**Closed by codders** 2024-05-13 16:00 UTC
